// Generated by Flexc++ V2.11.00 on Tue, 11 Apr 2023 21:21:38 +0200

#ifndef ArgScanner_H_INCLUDED_
#define ArgScanner_H_INCLUDED_

#include "ArgScannerbase.h"


// Scanner for ArgParser
class ArgScanner :
  public ArgScannerBase
{
  std::string currString;
  public:
    explicit ArgScanner(std::istream &in = std::cin, std::ostream &out = std::cout,
                        bool keepCwd = true);

    int lex();

  private:
    int lex_();
    int executeAction_(size_t ruleNr);

    void print();
    void preCode();

    void postCode(PostEnum_ type);
};

inline ArgScanner::ArgScanner(std::istream &in, std::ostream &out, bool keepCwd)
  :
  ArgScannerBase(in, out, keepCwd) {}


inline void ArgScanner::preCode()
{
  // optionally replace by your own code
}

inline void ArgScanner::postCode([[maybe_unused]] PostEnum_ type)
{
  // optionally replace by your own code
}

inline void ArgScanner::print()
{
  print_();
}


#endif // ArgScanner_H_INCLUDED_

